ASSUME CS:CODE, DS:DATA

DATA SEGMENT
NUMBERS DB 52H, 32H, 5AH, 13H, 6EH, 90H, 0BH, 73H, 67H, 33H
EVENNUM DB 0AH DUP(?)
COUNT EQU 10D
DATA ENDS

CODE SEGMENT
START:	MOV AX, DATA
		MOV DS, AX
		
		MOV CX, COUNT
		XOR AX, AX
		XOR DX, DX
		
		MOV SI, OFFSET NUMBERS
		MOV DI, OFFSET EVENNUM
	CHECKEVEN:
        MOV BL, [SI]
        MOV DL, BL
		ROR DX, 01
        JC NEXT
        MOV [DI], BL
		INC AX
        INC DI
        
NEXT:   INC SI
        LOOP CHECKEVEN 
		MOV BX,AX
		MOV AH,4CH
		INT 21H
CODE ENDS
END START
