ASSUME CS:CODE, DS:DATA
DATA SEGMENT
NUMBERS  DB  02H,03H,04H,00H,09H,0AH,03H,05H,1AH,0FH
COUNT    EQU 10D
DATA ENDS

CODE SEGMENT
START:  MOV AX,DATA
	    MOV DS,AX
        XOR AX,AX
        MOV CX,COUNT
        MOV SI,OFFSET NUMBERS
      LARGEST:CMP AL,[SI]
        JNC SKIP
        MOV AL,[SI]
      SKIP:
		INC SI
        LOOP LARGEST
		MOV BL,AL ;SO THAT BL NOW HAS LARGEST_NUMBER
        MOV AH,4CH
        INT 21H
CODE ENDS
END  START
